### ISSUE TITLE
Centering left-aligned text

### ISSUE THREAD

**Issue by trebird** [trebird/link-card#1]
Hi @thomasjbradley

Pretty much good to submit my link card, but I don't want to until I figure out how to center the dd's.
I just have them as text-align: center for now because it looks closer to the screenshots, but I know they are left-aligned. I've been experimenting with display and things, but I'm not sure how to get them to do it.

Thank you!

**Comment by thomasjbradley** [comment]
Have you tried using `inline-block` on the `<dd>` and `<dt>` tags?
